### ISSUE TITLE
ARM Release

### ISSUE THREAD

**Issue by Nosmoht** [julienlevasseur/terraform-provider-uname#1]
Hi @julienlevasseur ,

thanks a lot for this provider. Could you please create an ARM release too? I'm trying to find out if Terraform runs on `x86_64/amd64` or `arm64` machine so i can give correct information to `libvirt` provider as some things are different between both machines.

Thanks a lot

**Comment by hh** [comment]
@julienlevasseur may have scratched an itch 3 years ago that @Nosmoht and I are also experiencing!

Julien, let me know if you'd like some help publishing, or if you might be ok with some else else publishing for you.  Terraform Providers create an interesting ecosystem!

I'm trying to to detect the GO ARCH when on an M1 Mac to bootstrap coder...

From https://github.com/cncf-infra/coder-templates/blob/simple/simple/simple.tf#L18-L20
```
resource "coder_agent" "dev" {
  arch = data.uname.system.machine          # goInfo.GetInfo().Platform
  os   = data.uname.system.operating_system # goInfo.GetInfo().OS)
```

Results (on M1 Mac):
![image](https://user-images.githubusercontent.com/31331/223489286-8e277051-1433-482d-9856-12e808f357fe.png)

**Comment by julienlevasseur** [comment]
Hey @Nosmoht and @hh, thanks for bringing that issue !

To be honest, when I saw the comment from @Nosmoht, I didn't understand the problem right away since they were already some ARM release for this provider (Freebsd and GNU/Linux) and I decided to have a look when I had time.

But, with your reply @hh, I get the point, `darwin_arm64` was indeed not supported.
This provider have been lacking some love for the past couple years and it turns out that `goreleaser` now supports this architecture.

You can find the new `darwin_arm64` along with some new others OS/Arch combination in the latest release -> https://github.com/julienlevasseur/terraform-provider-uname/releases/tag/0.0.4

I don't have any ARM64 platform to test it, so, I'll keep the issue open until you confirm that this solve your situation.

Thank you for using this provider.

**Comment by hh** [comment]
I did a quick check using the following folder with the simplest `uname.tf` to output *os* and *arch*.

https://github.com/cncf-infra/coder-templates/tree/simple/simple/ss

However I seem to be getting null values. Anything I can do the check?

https://github.com/cncf-infra/coder-templates/blob/simple/simple/ss/nullname-terraform.tfstate#L25-L31

```terraform
terraform {
  required_providers {
    uname = {
      source  = "julienlevasseur/uname"
      version = "0.0.4"
    }
  }
}

data "uname" "system" {}

output "os" {
  description = "goInfo.GetInfo().OS as supplied by julienlevasseur/uname"
  value       = data.uname.system.operating_system
}

output "machine" {
  description = "goInfo.GetInfo().Platform as supplied by julienlevasseur/uname"
  value       = data.uname.system.machine
}
```

```shell
cat terraform.tfstate | jq '.resources[0]'
```

```json
{
  "mode": "data",
  "type": "uname",
  "name": "system",
  "provider": "provider[\"registry.terraform.io/julienlevasseur/uname\"]",
  "instances": [
    {
      "schema_version": 0,
      "attributes": {
        "id": null,
        "kernel_name": null,
        "kernel_release": null,
        "machine": null,
        "nodename": null,
        "operating_system": null
      },
      "sensitive_attributes": []
    }
  ]
}
```

**Comment by julienlevasseur** [comment]
I updated the goInfo version in the provider: https://github.com/julienlevasseur/terraform-provider-uname/releases/tag/0.0.5

Can you test again ?
If it still does not work, could you run this and share the output ?
```go
package main

   import (
	   "github.com/matishsiao/goInfo"
   )

   func main() {
		gi, _ := goInfo.GetInfo()
		gi.VarDump()
	 }
}
```
Thank you

**Comment by hh** [comment]
I updated to 0.0.5: https://github.com/cncf-infra/coder-templates/commit/a616bc85b8119526601a0567947163d1edd0db7f

```shell
 terraform apply -auto-approve                              
data.uname.system: Reading...
data.uname.system: Read complete after 0s

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

machine-notnull = "NOTNULL"
os-notnull = "NOTNULL"
```

I ran your code and here is the output:

```golang
package main
import "github.com/matishsiao/goInfo"

func main() {
	gi, _ := goInfo.GetInfo()
	gi.VarDump()
}
```

```
% go run ./main.go
GoOS: darwin
Kernel: Darwin
Core: 22.3.0
Platform: arm64
OS: Darwin
Hostname: Max.local
CPUs: 10
```

**Comment by julienlevasseur** [comment]
Thanks @hh for vaidating this.
I was also able to reproduce locally these `nil` values.

It seems that a lot of things have changed on how the Terraform Providers are build. This provider is out of date and does not work anymore with newer Terraform version.
I started a rewritting of it, I'll let you know when it is ready (couple days).

Thanks

**Comment by julienlevasseur** [comment]
@hh Update: Finally I took some time right away :smile: 

Here's the result of the first tests after the rewrite:
```
 terraform apply
data.uname_datasource.localhost: Reading...
data.uname_datasource.localhost: Read complete after 0s
local_file.file: Refreshing state... [id=55e9d2455a812971ce1581ae4637157d72ab5821]

Changes to Outputs:
  + os = "GNU/Linux"

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes


Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

os = "GNU/Linux"
```

I just pushed the `0.1.0` tag to generate new release. You should be able to test it once the workflow is completed: https://github.com/julienlevasseur/terraform-provider-uname/actions/runs/4369048038/jobs/7642391560

**Comment by hh** [comment]
On a linux amd64 box:

```
 terraform apply -auto-approve
data.uname.system: Reading...
data.uname.system: Read complete after 0s

Changes to Outputs:
  + machine = "x86_64"
  + os      = "GNU/Linux"

You can apply this plan to save these new output values to the Terraform state, without changing any real
infrastructure.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

machine = "x86_64"
machine-notnull = "NOTNULL"
os = "GNU/Linux"
os-notnull = "NOTNULL"
```

On M1 Mac:

```
$ terraform apply -auto-approve
data.uname.system: Reading...
data.uname.system: Read complete after 0s

Changes to Outputs:
  + machine = "arm64"
  + os      = "Darwin"

You can apply this plan to save these new output values to the Terraform state, without changing any real
infrastructure.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

machine = "arm64"
machine-notnull = "NOTNULL"
os = "Darwin"
os-notnull = "NOTNULL"
```

**Comment by hh** [comment]
@Nosmoht From my side I think 0.1.0 has brought ARM/M1 support (and inadvertently updated the provider to upstream terraform changes).

Thanks SO MUCH @julienlevasseur for your work here. It's helping unblock some big items on my plate.

Let me know if I can send you a meaningful thank-you gift somehow!

**Comment by julienlevasseur** [comment]
Excellent ! I'm glad it helps.

If you are interested in maintaining this provider (and since you mentioned you could be interested to help), I can make you a collaborator on this repository. Your help keeping this provider up-to-date would be the best thank-you gift I can imagine.
And no offence if you're not interested ;)

**Comment by hh** [comment]
That would be great @julienlevasseur ! I'll see if I can't setup a coder template for this so folks who are interested can spin up a collaborative environment with the code checked out (to assist in understanding the project, contributing, and creating PRs!)

**Comment by julienlevasseur** [comment]
Awesome, thank you ! You're now a collaborator. Thank you for your help with this project. Much appreciated !

**Comment by hh** [comment]
Here's the initial 'simple' template your work helped build. Eventually I'd like it to just-work on most Linux, OSX, and Windows boxes. https://github.com/cncf-infra/coder-templates/tree/main/simple#simple-template
